modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mysticalagriculture"
    mandatory=true
    versionRange="1.21.1-8.0.8,"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mysticalagradditions"
    mandatory=true
    versionRange="1.21.1-8.0.3,"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="productivelib"
    mandatory=true
    versionRange="1.21.0-0.1.9,"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="productivebees"
    mandatory=true
    versionRange="1.21.1-13.6.5,"
    ordering="AFTER"
    side="BOTH"